### ISSUE TITLE
Breaking several Recipe Types

### ISSUE THREAD

**Issue by fzzyhmstrs** [nvb-uy/Item_Obliterator#11]
With the newet Fabric version `Item_Obliterator-Fabric_Quilt-MC1.20.1-1.6.1hf`, several recipe types in our SMP from various mods are completely broken. Exmaple error messages:

Amethyst Imbuement Imbuing:
[message.txt](https://github.com/nvb-uy/Item_Obliterator/files/13328328/message.txt)

Adorn Brewing
[message2.txt](https://github.com/nvb-uy/Item_Obliterator/files/13328331/message2.txt)

For Amethyst Imbuement Imbuing at least, I don't even use the `craft` method.

**Comment by nvb-uy** [comment]
Fixed 1.70
