### ISSUE TITLE
compat with EMI/JEI? 

### ISSUE THREAD

**Issue by mateus3c** [nvb-uy/Item_Obliterator#17]
EMI crashes after blacklisting items, would it be possible to add compat for EMI?

Anyway, thank you for this amazing mod, I just discovered it today and It is literally everything I always wanted, now that I know item obliterator exists I will never play without it. thank you so much, finally I can remove overlaps!

**Comment by nvb-uy** [comment]
Coming on v2.0.0

**Comment by nvb-uy** [comment]
Implemented in 2.0.0
