### ISSUE TITLE
[1.20.1 Fabric] EMI Recipes still showing when present in Item Obliterator blacklist

### ISSUE THREAD

**Issue by gamerpotion** [nvb-uy/Item_Obliterator#2]
Hi, I was asked to report here as EMI is still showing blacklisted items - https://github.com/emilyploszaj/emi/issues/232

please could you take a look? thank you

**Comment by nvb-uy** [comment]
As shown in the mod page, IO only has direct compatibility with REI, which apparently also works with JEI

I don't use EMI myself so I have no interest in adding compatibility at the moment. If you want to you can make a PR to add it yourself

**Comment by gamerpotion** [comment]
Removed mod from pack, thanks anyway :)
