### ISSUE TITLE
Forge 1.20.1 | Items are removed from JEI tab but recipes still can point to them

### ISSUE THREAD

**Issue by Billnotic** [nvb-uy/Item_Obliterator#23]
Items removed via this mod disappear correctly from the right tab in JEI, but can still appear in the crafting previews.

**Comment by Billnotic** [comment]
This appears to also be an issue with the 1.20.1 fabric version as well.

**Comment by nvb-uy** [comment]
I'll work soon on a recipe ban that will remove them from loading instead of on runtime, which hopefully will fix them still appearing in JEI/REI/EMI
