### ISSUE TITLE
[Neoforge 1.20.1] Mod causing Embers Stamper to eat items/fluids inserted into it half the time

### ISSUE THREAD

**Issue by Tlp300** [nvb-uy/Item_Obliterator#24]
Having this mod installed along with Embers causes the Stamper to just outright delete any items/fluids into it half the time.

NeoForge version 47.1.96
Embers Rekindled 1.1.1
Item Obliterator 1.7.0

1. Install this mod and Embers
2. Place down Embers stamper base and stamper
3. Power it with Ember
4. Try right clicking items into the stamper base or inserting with hoppers/fluid pipes
5. Watch as it just disappears into the ether

Log attached: https://gist.github.com/Tlp300/923ada27e2f5b3d53dc0bf2118ce9f52

I didn't really see anything in the log though.

**Comment by nvb-uy** [comment]
Not entirely sure why this would happen, have you reported this to embers devs?

**Comment by nvb-uy** [comment]
Should be fixed by v2.2.0
