### ISSUE TITLE
Can't go higher than 221?

### ISSUE THREAD

**Issue by Sky88Dog** [nvb-uy/Item_Obliterator#25]
Trying to use this for a server, I get this crash report while opening my game
[crash-2024-02-03_09.28.28-fml.txt](https://github.com/nvb-uy/Item_Obliterator/files/14156373/crash-2024-02-03_09.28.28-fml.txt)

**Comment by nvb-uy** [comment]
send your config, you have a syntax errors in your file

**Comment by Sky88Dog** [comment]
[item_obliterator.json](https://github.com/nvb-uy/Item_Obliterator/files/14160839/item_obliterator.json)
Here you go, and thanks for helping.

**Comment by nvb-uy** [comment]
You have a missing comma at line 220 and an extra comma at the last line (441). Please use a proper JSON-compatible editor that will show syntax errors, like sublime text, notepad++ or VSCode

**Comment by Sky88Dog** [comment]
Thanks so much, It works now.
