### ISSUE TITLE
What command is needed to lock the enchantment book?

### ISSUE THREAD

**Issue by Krimatoria** [nvb-uy/Item_Obliterator#26]
What command is needed to lock the enchantment book?
I write the name of the item in the blacklist and it does not disappear
![image](https://github.com/nvb-uy/Item_Obliterator/assets/106809386/d393a3d3-3fa8-47a3-8764-08f32efc2e3a)
![image](https://github.com/nvb-uy/Item_Obliterator/assets/106809386/7710a5b6-7c63-45c0-b08f-6a2b794d7983)

**Comment by nvb-uy** [comment]
The end of herobrine is a forge only mod, so you're playing on forge.
v2.0.0 is the only version that supports NBT banning, and it hasn't yet been ported to Forge, so for now, this is not possible.
