### ISSUE TITLE
recipe isnt removed completely

### ISSUE THREAD

**Issue by luluthepogcat** [nvb-uy/Item_Obliterator#28]
when disabling items, it will only not appear in the search menu, if i were to click show uses on the item's material, the recipe will still show
![image](https://github.com/nvb-uy/Item_Obliterator/assets/154001303/5346b672-2567-49ad-a7e9-f1db3e31674e)

**Comment by luluthepogcat** [comment]
you can see that despite sup's rope got disabled, when i show use flax, it will still show recipe

**Comment by kerrschtein** [comment]
i'm having this too!

**Comment by memphismc** [comment]
also having this issue, item sure is removed, but the recipe for it is still there despite it clearly stating in the config that any item in "blacklist_items" gets removed from everything

**Comment by memphismc** [comment]
> > also having this issue, item sure is removed, but the recipe for it is still there despite it clearly stating in the config that any item in "blacklist_items" gets removed from everything
> 
> I even had to learn kubejs just to remove the recipe

in my case i am using better recipe book mod which might conflict with this

**Comment by Superdavid999** [comment]
Same here!

**Comment by nvb-uy** [comment]
Fixed on latest :)
