### ISSUE TITLE
Item blacklist not working

### ISSUE THREAD

**Issue by Shark10199** [nvb-uy/Item_Obliterator#29]
I tried to blacklist some items and it did not work. did I do it correctly? It looks like this:

"blacklisted_items": [
    "minecraft:amethyst_shard",
    "minecraft:netherite_sword,
    "minecraft:minecraft:diamond
  ],

**Comment by nvb-uy** [comment]
that's completely wrong, please use a JSON compatible text editor like VSCode or sublime text.

You're missing the final quotes on the 2nd and 3rd entries
