### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by HolyCartoon** [nvb-uy/Item_Obliterator#30]
After obtaining the item i blacklist (example: totem of undying) it automatically vanishes which for me it is normal. The crash happens after the vanish and searching the item on JEI and hovering the empty slot where the banned item should have been. I dont know if you were aware of it so i thought posting this was a good idea. Heres a video recording too along side with the crash report.

https://github.com/nvb-uy/Item_Obliterator/asset
[crash-2024-03-03_17.19.59-client.txt](https://github.com/nvb-uy/Item_Obliterator/files/14473508/crash-2024-03-03_17.19.59-client.txt)
s/162037431/5ee13bce-d90b-4878-933b-153d012c3360

**Comment by nvb-uy** [comment]
says page not found

**Comment by HolyCartoon** [comment]
> says page not found

huh i clicked it right after uploading it worked fine idk

**Comment by nvb-uy** [comment]
Send me your config, when the game crashes it's because your config has syntax errors. You can find these errors by using a code editor that supports json5, like VSCode
