### ISSUE TITLE
item entities

### ISSUE THREAD

**Issue by FinxdMC** [nvb-uy/Item_Obliterator#32]
blacklisted items stay in this frozen state where they can't be picked up, but still remain floating

is there plans to kill the dropped items as well? (there was one mod that did this called "Delete Item" that did exacly this, it's not updated to 1.20, though)

for example, i disabled crossbows, but piglins still drop them sometimes, it would be nicer if there was an option to get rid of the item entities too

**Comment by FinxdMC** [comment]
i was able to do something similar with datapack functions, but they really kill server performance, and there is no easy way to only execute the command when an item spawns

**Comment by nvb-uy** [comment]
The items floating and not being able to be picked up is caused by another mod. I'm not entirely sure why but the mod itself works as intended. It's probably something handling entities' ticks (Like Does it tick, does potato tick, no see no tick, etc)

**Comment by FinxdMC** [comment]
i tested it without any other mod (on forge and neoforge, both on 1.20.1) and they still keep floating

**Comment by darceno** [comment]
@nvb-uy at least in Forge 1.20.1, is not caused by another mod and happens with just Item Obliterator & Necronomicon installed.
