### ISSUE TITLE
Can I disable all items from a certain mods?

### ISSUE THREAD

**Issue by Panetina** [nvb-uy/Item_Obliterator#34]
I tried simplehats:* but it doesn't work, my game crashes.

**Comment by nvb-uy** [comment]
you'll need to use regex. Try "!simplehats:.*"

**Comment by nvb-uy** [comment]
if your game crashed tho, that's probably due to a bad syntax, please use a json compatible text editor like vscode

**Comment by Panetina** [comment]
1. I tried that too, still crashes for some reason
2. I tried to remove an item, its removed from being crafted, from being used and from JEI, but it still appears in the recipe book.

**Comment by nvb-uy** [comment]
Recipe book isn’t supported. It’s unconventional and has performance issues.

Can you send a crash log?
