### ISSUE TITLE
Obliterated Items Will Continuously "Respawn" before being destroyed

### ISSUE THREAD

**Issue by jlars789** [nvb-uy/Item_Obliterator#36]
This issue specifically is from the obliteration of Thermal Cultivation's Tomato, Onion, Rice, and Flax Seed items. These have a chance to randomly drop when destroying Grass. Despite being obliterated (confirmed as it is not in JEI or Creative inventory), these will still drop, but cannot be picked up. In addition, they will continuously be destroyed then "respawn" at their original spawn location every 30 ticks (estimation). This will continue until the instance is reset, even beyond the natural despawn timer.

Game Version: 1.20.1
Item Obliterator Version: 1.7.0

**Comment by FinxdMC** [comment]
late reply, but i had this same issue for months, until today, when i decided to try using the fabric version with sinytra connector, it seems to be working fine, it will just generate a new config file, so you'll need to paste the item names from the old one to the new one

**Comment by nvb-uy** [comment]
Fixed on latest
