### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by dupson9** [nvb-uy/Item_Obliterator#37]
hello, when i add items games crushes but if i only add one item it dont, do i do something wrong? please help guys!!!!!! today i need to start server for my friends! and i cant start it without baning this items! ps. im form poland 
(file)
[item_obliterator.json](https://github.com/nvb-uy/Item_Obliterator/files/14724086/item_obliterator.json)
screen from vsc (why text is red??!?)
![Zrzut ekranu 2024-03-22 153833](https://github.com/nvb-uy/Item_Obliterator/assets/164523297/9b669ffb-fe96-4587-b157-8dc4d8b02105)
and crash report!!1!!11!!
[crash-2024-03-22_15.26.16-fml.txt](https://github.com/nvb-uy/Item_Obliterator/files/14724104/crash-2024-03-22_15.26.16-fml.txt)

thanks for help from mountains!

**Comment by nvb-uy** [comment]
https://www.w3schools.com/js/js_json_syntax.asp
