### ISSUE TITLE
cant open the menu

### ISSUE THREAD

**Issue by rituals4mad** [nvb-uy/Item_Obliterator#38]
when i open Minecraft this pops up on my screen.
Item Obliterator (item_obliterator) encountered an error during the
common_setup event phase
java.lang.RuntimeException: Failed to initialize config field: INSTANCE

**Comment by nvb-uy** [comment]
Do you have Necronomicon API installed?

**Comment by rituals4mad** [comment]
yeah i do, but there were some weird code when downloading it. For forge it said: 
dependencies {
   implementation fg.deobf("maven.modrinth:necronomicon:${project.necronomicon_version}-forge")
}
I dont know what to use this for, any help? Ive tried looking up how to use the Necronomicon mod, but I couldnt find anything

**Comment by nvb-uy** [comment]
That’s to integrate necronomicon into mod projects, in CF/Modrinth, Necronomicon is just another mod like the rest, just install it like you did with item obliterator

**Comment by rituals4mad** [comment]
Yeah i did and put it in my mod folder, but im still getting that error pop up. Any idea why?

**Comment by nvb-uy** [comment]
Upload your logs to mclo.gs, and also send me your config file, it’s most likely an issue with the config

**Comment by rituals4mad** [comment]
hope i did this right. mcclogs said my forge verison was wrong i think? ive never used the website before but it said my forge version and minecraft version under analysis. 
[item_obliterator.json](https://github.com/nvb-uy/Item_Obliterator/files/14813762/item_obliterator.json)

**Comment by nvb-uy** [comment]
missing comma at line 26
