### ISSUE TITLE
Deletion does not work for large items IDs

### ISSUE THREAD

**Issue by xboct02** [nvb-uy/Item_Obliterator#40]
In a regular expression of the type "Iminecraft:.*_sword" will take into account only one variation of the subject. For large identifiers of the type "!minecraft:.*_copper" deleting all variations of copper blocks does not work.
I tried writing "!minecraft:.*.*.*_copper*." only minecraft:copper_block was deleted.
The last prepositions of the copper_'block type are also ignored'

**Comment by nvb-uy** [comment]
A dot will only match the next character, please use .*
