### ISSUE TITLE
Deleted blocks are displayed on the server

### ISSUE THREAD

**Issue by xboct02** [nvb-uy/Item_Obliterator#41]
It's no secret that items are cut only from available inventory, not from the game, but the big disadvantage of this mod is unsupportability on servers where everything is displayed as without the mod.

**Comment by nvb-uy** [comment]
It's item obliterator, not world block removal. Use block swap if you want to remove existing blocks, the mod works as intended.

**Comment by xboct02** [comment]
We are talking about inventory, hidden objects are displayed in the inventory when playing on the server.

**Comment by nvb-uy** [comment]
Hello, please use Block Swap. Item Obliterator only deletes items, not blocks. It’s not the purpose of the mod and I won’t add it as a feature because block swap already exists

**Comment by xboct02** [comment]
Hidden items are displayed in the inventory when playing on the server.I don't need to delete them.
