### ISSUE TITLE
Item not completely hidden from JEI

### ISSUE THREAD

**Issue by Magi1053** [nvb-uy/Item_Obliterator#44]
I have noticed that while the mod does disable the recipe for the item so that it can no longer be crafted, and it hides the item itself from JEI, the recipe is still in JEI. Fore example, if I disable the Sea Lantern Slabs, and then I hover of the Sea Lantern and Show Uses (press U), then I can still see the recipe to craft the Sea Lantern Slabs.

**Comment by SoftboyMC** [comment]
Happening in version 1.19.2 1.6.1 and 1.6.2. Also please indicate in the mod description that EMI support is only for 2.0+, or port 2.0 to 1.19.2

**Comment by nvb-uy** [comment]
2.2.1 has been ported to 1.19.2, uploading soon

**Comment by Magi1053** [comment]
Hi, I am having this issue on 1.20.1

**Comment by darceno** [comment]
Having the same issue on Forge 1.20.1 with the latest version
