### ISSUE TITLE
Cutting Boards from Farmer's Delight are unusable when Item Obliterator is installed

### ISSUE THREAD

**Issue by mintynoura** [nvb-uy/Item_Obliterator#45]
It's as if all the recipes got deleted. The Cutting tab in EMI is gone and every item will show a "this isn't cuttable" text when attempting to use the Board. This is on a fresh Fabric instance, with an unchanged config, I have not attempted to obliterate any items yet.

Mod versions are:
Fabric API: 0.92.1
Necronomicon: 1.4.2
Item Obliterator: 2.2.0
Farmer's Delight Refabricated: 2.1.1

![image](https://github.com/nvb-uy/Item_Obliterator/assets/107040228/9a7764a7-d2ab-4f27-9288-e26f3ff758f7)

Edit: I should also add that the logs do not mention anything about the recipes or the Cutting Board.

**Comment by nvb-uy** [comment]
Fixed it in v2.2.1, will upload in a bit

**Comment by nvb-uy** [comment]
Uploaded
