### ISSUE TITLE
Item Obliterator not working with REI

### ISSUE THREAD

**Issue by McGodMan** [nvb-uy/Item_Obliterator#5]
### Versions
Minecraft: 1.20.1
IO: [1.4.0](https://modrinth.com/mod/item-obliterator/version/1.4.0)
REI: [12.0.645](https://modrinth.com/mod/rei/version/12.0.645+fabric)

### Issue
Items still show in REI after being put on the Item Obliterator blacklist

### Example
Blacklist was updated before minecraft was started
![image](https://github.com/nvb-uy/Item_Obliterator/assets/37338326/3fc48726-7ab4-4ebd-8117-fd017e1fea60)

### Minimum mods required to repeat
![image](https://github.com/nvb-uy/Item_Obliterator/assets/37338326/ca793895-8a9e-47d1-8678-66a2e63a6c2f)

Thanks in advance

**Comment by nvb-uy** [comment]
Cannot reproduce, tested on Prominence II FABRIC with +20 items in the list and they all disappear from REI
