### ISSUE TITLE
Crashes when using blacklisted_nbt

### ISSUE THREAD

**Issue by Galysso** [nvb-uy/Item_Obliterator#50]
I tried using the example from the config file `Potion:"minecraft:regeneration"` and the example given in [https://github.com/nvb-uy/Item_Obliterator/issues/48](https://github.com/nvb-uy/Item_Obliterator/issues/48) and both makes the game crashing at startup.

Here is a crash-report: [https://mclo.gs/RV6u7P5](https://mclo.gs/RV6u7P5)

(Forge 1.20.1)

**Comment by nvb-uy** [comment]
Please escape the quotes using \

**Comment by BIG-Viljo** [comment]
Could you please elaborate a bit further? Neither "Potion:\"minecraft:regeneration\"" or Potion:\"minecraft:regeneration\" works. The former loads the game, but potions of regeneration are still present and the former straight up crashes.

**Comment by nvb-uy** [comment]
Please escape the quotes by adding a \ or else the json will freak out.

**Comment by BIG-Viljo** [comment]
My bad, github escaped the quotes. I tried `"Potion:\"minecraft:regeneration\""` and `Potion:\"minecraft:regeneration\"`, but to no avail.

**Comment by tylrcodes** [comment]
> Potion:\"minecraft:regeneration\"

also needing help with this

**Comment by MeowingInsanely** [comment]
Having same issues for removing a modded item:

{id: "botania:blood_pendant", tag: {brewKey: "botania:bloodthirst"}

Inserting the code in:
```
  "blacklisted_nbt": [
  // CODE HERE
    ],
```

Code that I've tried but is causing a crash:
```
brewKey:\"botania:bloodthirst\"
brewKey:\"botania:bloodthirst"
brewKey:\"botania:bloodthirst"\
```

Works but does not remove items:
```
"brewKey:\"botania:bloodthirst\""
```

**Comment by eithli** [comment]
> They seem to be using a JSON deserializer for a JSON5 file :)

soooo, what’s the correct way to format it?

**Comment by Blobikium** [comment]
any solution?

**Comment by Midnight-GHub** [comment]
any solution yet?
