### ISSUE TITLE
Obliterate Specific Items From Loot Tables

### ISSUE THREAD

**Issue by yunus-cakir** [nvb-uy/Item_Obliterator#53]
Hi! We are using a Coin Economy mod in our modded survival multiplayer server but some of our players are finding 100x (Gold) Coin in loot chests and the mod creators doesn't help us so is there a way to remove a specific item from loot tables? I'd really appreciate if you could help me :)
The pack: https://modrinth.com/modpack/valley
![image](https://github.com/nvb-uy/Item_Obliterator/assets/83448525/c026cf81-1177-4285-b486-1dc1877e94a0)

**Comment by nvb-uy** [comment]
Hi, I have not added this feature yet but I might do in the future. For now I suggest you to make a datapack to remove them from loot tables, and in the case it's being injected to all loot tables, ask the mod author to add a config to disable that (similar how mods like simply swords and the rpg series do)
