### ISSUE TITLE
Regex for remove all items from one mod except one

### ISSUE THREAD

**Issue by ArcaneAlloy** [nvb-uy/Item_Obliterator#54]
Hello! I would like to know if it is possible to create a regex to ban all the items of a mod, except one. For example, all the items from the Create mod except the "create:experience_nugget"

**Comment by nvb-uy** [comment]
^(?!.*\bcreate:experience_nugget\b).+$

**Comment by HoodBlah** [comment]
What if there are multiple items I want to keep? Can I use this multiple times in the "blacklisted_items" section? Like this:

^(?!.*\bpneumaticcraft:item_life_upgrade\b).+$,
^(?!.*\bpneumaticcraft:armor_upgrade\b).+$,
^(?!.*\bpneumaticcraft:magnet_upgrade\b).+$
