### ISSUE TITLE
Creative Tab hiding is incompatible with an unknown mod

### ISSUE THREAD

**Issue by ThariCorvy** [nvb-uy/Item_Obliterator#56]
Greetings! I've come to report an issue I'm having with this tool.
It appears I have typed the item ID's correctly in the config, but recipes persist, and the items are still in Creative Tabs and JEI.
Curiously, obtaining the item and putting it in the inventory is possible until I close the menu, that's when said item is obliterated from my inventory. Even though it does that, it is claimed that items put in the config are meant to be completely hidden and restrained from obtaining them by any means. That's what I desire, but it's not what I'm getting.

For reference, here's the config file I set:

{
  // -----------------------------------------------------------
  //              Item Obliterator by ElocinDev
  // -----------------------------------------------------------
  //  
  // How to add items?
  //   - They are json strings, so you need to separate each
  //     entry with a comma, except the last
  //   - If you start an entry with !, it will be treated as a regular expression
  //     Example: "!minecraft:.*_sword" to disable all swords
  //  
  // -----------------------------------------------------------
  // Do not touch this
  "configVersion": 2,
  // -----------------------------------------------------------
  // Items here will be unusable completely
  //    Example: minecraft:diamond
  "blacklisted_items": [
    "minecraft:shield",
	"quark:rope",
	"supplementaries:rope",
	"aquamirae:golden_moth_in_a_jar",
	"createcasing:acacia_shaft",
	"createcasing:andesite_encased_acacia_shaft",
	"createcasing:andesite_encased_bamboo_shaft",
	"createcasing:bamboo_shaft",
	"createcasing:andesite_encased_birch_shaft",
	"createcasing:birch_shaft",
	"createcasing:andesite_encased_cherry_shaft",
	"createcasing:cherry_shaft",
	"createcasing:andesite_encased_crimson_shaft",
	"createcasing:crimson_shaft",
	"createcasing:andesite_encased_spruce_shaft",
	"createcasing:spruce_shaft",
	"createcasing:andesite_encased_dark_oak_shaft",
	"createcasing:dark_oak_shaft",
	"createcasing:andesite_encased_jungle_shaft",
	"createcasing:jungle_shaft",
	"createcasing:andesite_encased_oak_shaft",
	"createcasing:oak_shaft",
	"createcasing:andesite_encased_warped_shaft",
	"createcasing:warped_shaft",
	"createcasing:andesite_encased_mangrove_shaft",
	"createcasing:mangrove_shaft",
	"create_dd:magnet",
	"alexscaves_torpedoes:pocket_magnet",
	"irons_spellbooks:firefly_jar",
	"createaddition:electric_motor",
	"createaddition:alternator",
	"createaddition:rolling_mill",
	"createaddition:connector",
	"createaddition:small_light_connector",
	"createaddition:large_connector",
	"createaddition:redstone_relay",
	"createaddition:barbed_wire",
	"createaddition:tesla_coil",
	"createaddition:electrum_amulet",
	"createaddition:electrum_ingot",
	"createaddition:electrum_nugget",
	"createaddition:electrum_sheet",
	"createaddition:copper_wire",
	"createaddition:iron_wire",
	"createaddition:gold_wire",
	"createaddition:electrum_wire",
	"createaddition:spool",
	"createaddition:copper_spool",
	"createaddition:iron_spool",
	"createaddition:gold_spool",
	"createaddition:electrum_spool",
	"createaddition:festive_spool",
	"createaddition:copper_rod",
	"createaddition:iron_rod",
	"createaddition:gold_rod",
	"createaddition:electrum_rod",
	"createaddition:brass_rod",
	"alexsmobs:banana",
	"alexsmobs:banana_peel",
	"neapolitan:milk_bottle",
	"iter_rpg:cattail",
	"create_interactive:buffer_stop",
	"create_things_and_misc:portable_whistle",
	"create_things_and_misc:netherite_portable_whistle",
	"create_things_and_misc:acacia_sail",
	"create_things_and_misc:bamboo_sail",
	"create_things_and_misc:birch_sail",
	"create_things_and_misc:cherry_sail",
	"create_things_and_misc:chorus_sail",
	"create_things_and_misc:crimson_sail",
	"create_things_and_misc:dark_oak_sail",
	"create_things_and_misc:jaboticaba_sail",
	"create_things_and_misc:jungle_sail",
	"create_things_and_misc:mangrove_sail",
	"create_things_and_misc:oak_sail",
	"create_things_and_misc:ramboutan_sail",
	"create_things_and_misc:spruce_sail",
	"create_things_and_misc:warped_sail",
	"create_things_and_misc:train_buffer",
	"create_things_and_misc:train_stop",
	"create_things_and_misc:train_sing",
	"create_things_and_misc:train_sing_2",
	"create_things_and_misc:train_sing_3",
	"create_things_and_misc:train_sing_4",
	"create_things_and_misc:train_sing_5",
	"create_things_and_misc:train_sing_yellow_1",
	"create_things_and_misc:train_sing_yellow_2",
	"create_things_and_misc:train_sing_yellow_3",
	"create_things_and_misc:train_sing_yellow_4",
	"create_things_and_misc:train_sing_yellow_5",
	"create_things_and_misc:redsing",
	"create_things_and_misc:redsing_1",
	"create_things_and_misc:redsing_2",
	"create_things_and_misc:green_sing",
	"create_things_and_misc:green_sing_1",
	"create_things_and_misc:green_sing_2",
	"create_things_and_misc:green_sing_3",
	"create_things_and_misc:green_sing_4",
	"create_things_and_misc:green_sing_5",
	"create_things_and_misc:green_sing_6",
	"create_things_and_misc:speed_25",
	"create_things_and_misc:speed_50",
	"create_things_and_misc:speed_75",
	"create_things_and_misc:speed_100",
	"create:bar_of_chocolate",
	"createaddition:chocolate_cake"
  ],
  // -----------------------------------------------------------
  // Removes an item if it contains certain nbt tag. If the whole entry (or expression) is present, the item gets removed.
  // Use with caution! This is a very expensive operation and can cause lag if you have a lot of items blacklisted.
  // 	
  // 	 Example to disable a regeneration potion: Potion:"minecraft:regeneration"
  // 	
  // 	 You can also use regular expressions by starting the value with !
  "blacklisted_nbt": [],
  // -----------------------------------------------------------
  // Items here will not be able to be right-clicked (Interact)
  //    Example: minecraft:apple
  "only_disable_interactions": [],
  // -----------------------------------------------------------
  // Items here will not be able to be used to attack
  //    Example: minecraft:diamond_sword
  "only_disable_attacks": [],
  // -----------------------------------------------------------
  // Items here will get their recipes disabled
  // Keep in mind this already is applied to blacklisted items
  "only_disable_recipes": [],
  // -----------------------------------------------------------
  // If true, the mod will use a hashset to handle the blacklisted items
  // This is a more optimized approach only if you have a lot of items blacklisted (20 or more is recommended)
  // If you just have a small amount of items blacklisted, keep this false
  //  
  // [!] Enabling this will disable all regular expressions
  // [!] Does not apply to NBT, only item blacklist / interaction / attack
  "use_hashmap_optimizations": true
}

A picture of the Vanilla Shield still having recipes despite being the first item I blacklisted:
![image](https://github.com/nvb-uy/Item_Obliterator/assets/139649594/0352c427-c915-470f-b54b-b380ef44cd50)

A picture of Wooden Shaft Variants I'm certain I did not misspell in the blacklist:
![image](https://github.com/nvb-uy/Item_Obliterator/assets/139649594/46e43588-5516-4722-82a1-332a868bccf9)

A picture of the Create: Crafts & Additions creative tab which most items I blacklisted due to Create: New Age's existance:
![image](https://github.com/nvb-uy/Item_Obliterator/assets/139649594/641c3e04-5356-40ba-888c-c1331dd7de51)

A picture of me searching for "Rope" items, Quark's Rope Coil has been obliterated successfully:
![image](https://github.com/nvb-uy/Item_Obliterator/assets/139649594/e635ced8-f1ca-4395-9bdd-5bed8a67c1b4)

But not really.
![image](https://github.com/nvb-uy/Item_Obliterator/assets/139649594/bf76461b-b318-403b-88d9-fdeffda0cfb2)

This modpack I'm developing is an update of a 1.19.2 modpack I was making before, which also used Item Obliterator, and had almost the same amount of mods installed.

**Comment by nvb-uy** [comment]
try disabling hashmap optimizations?

Also keep in mind that REI/EMI support does not exist in forge

**Comment by ThariCorvy** [comment]
I tried disabling hashmap optimizations, and the issue still persists.
Also, I do not have REI/EMI installed, only JEI, if it's different.

**Comment by nvb-uy** [comment]
Please send logs

Besides that, could you try this with the minimum amounts of mods installed? Just JEI, Item Obliterator, and the mods (& dependencies) you want to ban. I believe this might be another mod that is conflicting with item obliterator's creative tab removal, which would also make it not be removed from JEI as JEI only displays the items from that are on creative tabs

**Comment by ThariCorvy** [comment]
Here's the latest log, meanwhile, I'll follow your instructions, so just give me a moment
[2024-06-25-1.log](https://github.com/user-attachments/files/15980364/2024-06-25-1.log)

**Comment by ThariCorvy** [comment]
Doing as you instructed, the items I've blacklisted have been obliterated as intended, but I have no clue what mod could be conflicting with the tool,,

**Comment by nvb-uy** [comment]
There's nothing on the logs so your best bet to find this culprit is doing a binary search, I'd really appreciate if you can tell me which mod is so I can try to do a fix from my end, although it's probably an external issue from a mod overwriting methods which sadly causes a lot of incompats :p

**Comment by ThariCorvy** [comment]
Alright, I'll try my best!

**Comment by ThariCorvy** [comment]
Tell me, is it because I'm running on Forge 47.3.1 instead of 47.1.3?
I heard something about the latter being best for compatibility for modpacks.

**Comment by nvb-uy** [comment]
It could be some weird lexforge shenanigans, I personally use neoforge for my 1.20.1 modpack and item obliterator works pretty well, although i don't use neither ccc bridge nor terralith

**Comment by nvb-uy** [comment]
Okay I think I know why it's causing this.

The mod has an empty "mixin.refmap.json" which I had a report from another create addon that had this same issue, if you delete that empty refmap the mod might work again along it

**Comment by nvb-uy** [comment]
Fixed on v2.3.1!

**Comment by antonhibl** [comment]
@nvb-uy will this fix be backported to 1.19.2? I am running this mod on Forge 1.19.2 and experiencing the same issue presumably because I have CC: Create Bridge in my pack; right now it seems my only solutions are to remove CC: Create Bridge, remove Item Obliterator, or manually unarchive CC: Create Bridge and delete the empty refmap file and then repackage the jar myself. None of those options seem particularly attractive to me...
