### ISSUE TITLE
[1.21.1] NeoForge support please and thank you! 🦊

### ISSUE THREAD

**Issue by Cixon** [nvb-uy/Item_Obliterator#75]
This honestly the only good item blacklisting mod out there that works for me.

**Comment by Cixon** [comment]
works for sinytra connector

**Comment by Mariosonicman91** [comment]
I tried Sinytra connector, it said there was an incompatible mixin on startup, how did you do this???

**Comment by Mariosonicman91** [comment]
![Image](https://github.com/user-attachments/assets/c9574274-0448-454d-ad5e-dbf2679079e6)

How?
