### ISSUE TITLE
`InvalidInjectionException` in fabric 1.20.1

### ISSUE THREAD

**Issue by SettingDust** [nvb-uy/Item_Obliterator#8]
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on item_obliterator$discardItemEntities could not find any targets matching 'tick' in net.minecraft.class_1542. Using refmap Item_Obliterator-Fabric_Quilt-refmap.json [PREINJECT Applicator Phase -> item_obliterator.fabricmixins.json:ItemEntityMixin from mod item_obliterator -> Prepare Injections ->  -> handler$gki000$item_obliterator$discardItemEntities(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]`

**Comment by nvb-uy** [comment]
update the mod

**Comment by SettingDust** [comment]
> update the mod

Item_Obliterator-Fabric_Quilt-MC1.20.1-1.5.0.jar

**Comment by nvb-uy** [comment]
download it from forge, not sure if it was updated on morti tbh

**Comment by SettingDust** [comment]
> download it from forge, not sure if it was updated on morti tbh

It's 1.5.0 on CF as well. Is it different?

**Comment by nvb-uy** [comment]
Fixed as of latest
